### ISSUE TITLE
REPORTE DE PRACTICA DLL

### ISSUE THREAD

**Issue by Rigoberto2001** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Rigoberto2001#2]
[REPORTEPRACTICA_DLL_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Rigoberto2001/files/6339108/REPORTEPRACTICA_DLL_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by garaudy12** [comment]
Calificación: 19 puntos

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
